version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    stdin_open: true
    ports:
      - 3300:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
